# Generated by Django 4.2.30 on 2026-08-12 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_user_managers_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_breakdowns', to='store.order'),
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentTransaction',
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
