# Generated by Django 6.1 on 2026-09-05 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_auditlog_user_remove_payment_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='store.role'),
        ),
        migrations.AlterField(
            model_name='rolepermissions',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_rel', to='store.role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'مشتري (Customer)'), ('store_admin', 'تاجر / صاحب متجر (Store Owner)'), ('driver', 'كابتن توصيل (Driver)'), ('admin', 'مدير النظام (Admin)')], db_index=True, default='customer', max_length=20),
        ),
    ]
